### ISSUE TITLE
 Freezes indefinitely using epicscorelibs > 7.0.5.99.1.0a2

### ISSUE THREAD

**Issue by RJCD-Diamond** [DiamondLightSource/aioca#56]
When using newer version of epicscorelibs, it freezes indefinitely when using caget or camonitor. No error messages are shown. Issues seems to come from:

cadef.ca_context_create(1)

## Steps To Reproduce
Steps to reproduce the behaviour:
python3.11
pip install aioca

Run this script:

## script
    from aioca import caget, camonitor, run

    PV = "BL22I-MO-FSWT-01:YAW.RBV"
  
    async def do_stuff():
  
        # Print out the value reported by PV2.
        print(await caget(PV,timeout=1))
  
        # Monitor PV3, printing out each update as it is received.
        def callback(value):
            print('callback', value)
  
        camonitor(PV, callback)
  
    # Now run the camonitor process until interrupted by Ctrl-C.
    run(do_stuff(), forever=True)

**Comment by AlexanderWells-diamond** [comment]
Could you please confirm what version(s) of `aioca` and `epicscorelibs` you have used for this?

Also, when I try and run your script I get an error that `forever` is an unrecognised keyword of the `asyncio.run()` method. Could you please clarify what this function is supposed to be?

**Comment by RJCD-Diamond** [comment]
aioca  1.8.1
epicscorelibs = 7.0.7.99.1.1

This script is a modified version of the one in the documentation, with the PVs set to a real PV and the caget omitted. I had not included my imports. I have added them for clarity. The run command seems to be imported from aioca. 

 https://diamondlightsource.github.io/aioca/main/tutorials/intro.html
 
 Having tested further, and created a new venv. I can no longer get any version of epicscorelibs to not freeze indefinitely

**Comment by RJCD-Diamond** [comment]
Through more investigation the non-working venv uses= epicscorelibs/lib/libca.so.7.0.5.99.1, and the working one uses epicscorelibs/lib/libca.so.7.0.1.99.14

Running on RHEL on my workstation

**Comment by AlexanderWells-diamond** [comment]
I'm afraid I don't understand what you mean. As you've noticed, the `libCa` version is compiled into `epicscorelibs`, and should not be being installed separately. `epicscorelibs==7.0.7.99.1.1` should have an associated `libCa==7.0.7.99.1`.  

It is quite believeable that if you have somehow got an `epicscorelibs` version that is trying to use the wrong `libCa` version that you would see these infinite hangs - EPICS generally doesn't work well when versions are mixed.

**Comment by RJCD-Diamond** [comment]
Let me clarify. I installed the latest version of aioca. After finding it freezes, I traced the problem to epicscorelibs. 

I installed the oldest working version of epicscorelibs, then updated until it stopped working (all via pip). The newest working version I have is 7.0.5.99.1.0a2, but ONLY when using 7.0.1.99.14 libCa. It seems 7.0.1.99.14 libCa was not deleted for some reason upon updating.

**Comment by AlexanderWells-diamond** [comment]
I'm somewhat surprised that much works when updating epicscorelibs without also updating (downgrading) aioca - the current release of aioca requires `epicscorelibs >= 7.0.3.99.4.0`, and the versions you reference indicate that they don't meet that requirement.

Could you please drop me an email and then perhaps I can investigate directly on your machine. Thanks.

**Comment by AlexanderWells-diamond** [comment]
We've investigated this issue and found it was environmental; another process was setting `LD_PRELOAD` to specify a version of the `libCom` library. That version was incompatible with more recent versions of `epicscorelibs`. Removing this environment setting fixes the issue.
